version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 533048344608.dkr.ecr.ap-south-1.amazonaws.com
     
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t test .
      - docker tag test:latest 533048344608.dkr.ecr.ap-south-1.amazonaws.com/test:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 533048344608.dkr.ecr.ap-south-1.amazonaws.com/test:latest
  artifacts:
    files:
      - 'imagedefinitions.json'